name: Build Wheels

on:
  push:
    # branches: [ main ]
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.20.0
      env:
        # CIBW_BUILD: 'cp39-* cp310-* cp311-* cp312-*'
        CIBW_SKIP: '*win32 *i686'   # Don't build for 32-bit
        CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=10.15   # force MacOS version 10.15+ for c++17 support
    
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./wheelhouse/*.whl

    - name: Set up Python for twine
      if: runner.os == 'macOS'   # Only needed on MacOS
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Publish to PyPI
      # if: runner.os != 'macOS'   # This does not work on MacOS yet
      run: |
        python -m pip install twine
        twine upload --skip-existing --non-interactive -u __token__ -p ${{ secrets.PYPI_TOKEN }} wheelhouse/*.whl

# Works only on Linux
#    - name: Publish to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_TOKEN }} 
#        packages-dir: wheelhouse/

